apiVersion: v1
kind: ConfigMap
metadata:
  name: rezk-fit-hub-config
  namespace: rezk-fit-hub-prod
data:
  config.json: |
    {
      "API_BASE_URL": "https://api.rezkenterprise.com",
      "ENVIRONMENT": "production"
    }
