apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rezk-fit-hub-pdb
  namespace: rezk-fit-hub-prod
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: rezk-fit-hub
      component: frontend
