/**
 * Centralized Real-time System Events Registry.
 */
export const SOCKET_EVENTS = {
    CLIENT_CREATED: 'CLIENT_CREATED',
    CLIENT_UPDATED: 'CLIENT_UPDATED',
    CLIENT_DELETED: 'CLIENT_DELETED',
    
    TASK_CREATED: 'TASK_CREATED',
    TASK_UPDATED: 'TASK_UPDATED',
    TASK_COMPLETED: 'TASK_COMPLETED',
    
    MESSAGE_SENT: 'MESSAGE_SENT',
    MESSAGE_READ: 'MESSAGE_READ',
    MESSAGE_TYPING: 'MESSAGE_TYPING',
    MESSAGE_STOPPED_TYPING: 'MESSAGE_STOPPED_TYPING',
    MESSAGE_EDITED: 'MESSAGE_EDITED',
    MESSAGE_DELETED: 'MESSAGE_DELETED',
    MESSAGE_REACTION_ADDED: 'MESSAGE_REACTION_ADDED',
    MESSAGE_REACTION_REMOVED: 'MESSAGE_REACTION_REMOVED',
    PRESENCE_UPDATED: 'PRESENCE_UPDATED',
    MESSAGES_READ: 'MESSAGES_READ',
    
    APPOINTMENT_CREATED: 'APPOINTMENT_CREATED',
    APPOINTMENT_UPDATED: 'APPOINTMENT_UPDATED',
    APPOINTMENT_DELETED: 'APPOINTMENT_DELETED',
    APPOINTMENT_LOCKED: 'APPOINTMENT_LOCKED',
    APPOINTMENT_UNLOCKED: 'APPOINTMENT_UNLOCKED',
    CALENDAR_PRESENCE_UPDATED: 'CALENDAR_PRESENCE_UPDATED',
    
    NOTIFICATION_CREATED: 'NOTIFICATION_CREATED',
    NOTIFICATION_READ: 'NOTIFICATION_READ',
    
    CALENDAR_UPDATED: 'CALENDAR_UPDATED',
    
    DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
    PROFILE_UPDATED: 'PROFILE_UPDATED',
    SYSTEM_BROADCAST: 'SYSTEM_BROADCAST',
    
    // Sprint 4.4 Collaboration Suite
    COMMENT_CREATED: 'COMMENT_CREATED',
    COMMENT_UPDATED: 'COMMENT_UPDATED',
    COMMENT_DELETED: 'COMMENT_DELETED',
    MENTION_CREATED: 'MENTION_CREATED',
    ENTITY_LOCKED: 'ENTITY_LOCKED',
    ENTITY_UNLOCKED: 'ENTITY_UNLOCKED',
    ENTITY_EDITING: 'ENTITY_EDITING',
    MERGE_REQUEST: 'MERGE_REQUEST',
    MERGE_ACCEPTED: 'MERGE_ACCEPTED',
    MERGE_REJECTED: 'MERGE_REJECTED',
    ACTIVITY_CREATED: 'ACTIVITY_CREATED',

    ORGANIZATION_CREATED: 'ORGANIZATION_CREATED',
    ORGANIZATION_UPDATED: 'ORGANIZATION_UPDATED',
    INVITATION_SENT: 'INVITATION_SENT',
    INVITATION_ACCEPTED: 'INVITATION_ACCEPTED',
    INVITATION_DECLINED: 'INVITATION_DECLINED',
    MEMBER_JOINED: 'MEMBER_JOINED',
    MEMBER_REMOVED: 'MEMBER_REMOVED',
    ROLE_CHANGED: 'ROLE_CHANGED',
    TEAM_CREATED: 'TEAM_CREATED',
    TEAM_UPDATED: 'TEAM_UPDATED',
    TEAM_DELETED: 'TEAM_DELETED',

    INVOICE_GENERATED: 'INVOICE_GENERATED',
    INVOICE_PAID: 'INVOICE_PAID',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    SUBSCRIPTION_RENEWED: 'SUBSCRIPTION_RENEWED',
    COUPON_APPLIED: 'COUPON_APPLIED',
    REFUND_COMPLETED: 'REFUND_COMPLETED',

    AI_PROCESSING_STARTED: 'AI_PROCESSING_STARTED',
    AI_PROCESSING_FINISHED: 'AI_PROCESSING_FINISHED',
    STREAMING_RESPONSES: 'STREAMING_RESPONSES',
    CONVERSATION_UPDATES: 'CONVERSATION_UPDATES',

    WEBHOOK_RECEIVED: 'WEBHOOK_RECEIVED',
    SYNC_STARTED: 'SYNC_STARTED',
    SYNC_FINISHED: 'SYNC_FINISHED',
    SYNC_FAILED: 'SYNC_FAILED',
    PROVIDER_CONNECTED: 'PROVIDER_CONNECTED',
    PROVIDER_DISCONNECTED: 'PROVIDER_DISCONNECTED'
};

export default SOCKET_EVENTS;
